services:
  postgres:
    restart: always
    build:
      context: ./
    container_name: simple_blog
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./01_init.sh:/docker-entrypoint-initdb.d/01_init.sh:cached
      - ./init:/usr/src/init:cached
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge